version: '3.8'

services: 
  mariadb:
    image: mariadb:10.6.5
    # 以下、要指定
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
      - TZ=Asia/Tokyo
    volumes:
      - ./mariadb/mariadb_data:/var/lib/mysql
    tty: true
  
  django:
    build: ./django
    # 以下、要指定
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
      - DEFAULT_FROM_EMAIL=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - BEARER_TOKEN=
      - TEST_USER_NAME=
      - TEST_USER_PASS=
    volumes:
      - ./django:/django
    ports: 
      - 8000:8000
    depends_on:
      - mariadb
    #tty: true
    command: bash -c "sleep 2 && python3 manage.py runserver 0.0.0.0:8000"
