# Generated by Django 4.0.2 on 2022-06-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=256)),
                ('author_id', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('media_urls', models.TextField()),
                ('emb_html', models.TextField()),
                ('emb_url', models.TextField()),
            ],
        ),
    ]
