# Generated by Django 4.0.2 on 2022-06-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_twitterpost_created_at_twitterpost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterpost',
            name='tweet_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
