# Generated by Django 4.0.2 on 2022-06-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_twitterlike_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterlike',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.twittercategory'),
        ),
    ]
