# Generated by Django 4.0.2 on 2022-06-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_twitterlike_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterlike',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.twittercategory'),
        ),
    ]
