# Generated by Django 4.0.2 on 2022-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_twittervisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterpost',
            name='author_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='tweet_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
